version: '3.8'

services:
  inventory-service:
    container_name: inventory_service_django
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: inventory_service
      POSTGRES_USER: inventory_service
      POSTGRES_PASSWORD: inventory_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
