# Generated by Django 5.0.2 on 2024-02-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField()),
                ("item_code", models.CharField(max_length=100)),
                (
                    "inventory_type",
                    models.CharField(default="consumable", max_length=50),
                ),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
    ]
