# Generated by Django 5.0.2 on 2024-02-19 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_service", "0002_playerinventory_created_playerinventory_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerinventory",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="playerinventory",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
